version: "3"
services:
  minne_database:
    container_name: minne_database
    image: postgres:15
    volumes:
      - ./.docker_volumes/postgres_data:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_USER=minne
      - POSTGRES_PASSWORD=debugpassword
      - POSTGRES_DB=minne
    restart: "unless-stopped"
    networks:
      - minne
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U minne" ]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  minne:
    driver: bridge

